// src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";
import {css} from '../assets/Hangeuljaemin4-Regular.otf'
function App() {
	const [count, setCount] = useState(0);
	console.log(css);
	return (
		<div className="App" style={{
			fontFamily: `'${css.family}'`
		}}>
			<div>
				<a href="https://reactjs.org" target="_blank" rel="noreferrer">
					<img src={reactLogo} className="logo react" alt="React logo" />
				</a>
			</div>
			<h1>Rspack + React + TypeScript</h1>
			<div className="card">
				<button onClick={() => setCount(count => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<p className="read-the-docs">
				Click on the Rspack and React logos to learn more
			</p>
		</div>
	);
}

export default App;

// src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import { css } from '../assets/Hangeuljaemin4-Regular.otf'
</script>

<template>
  <div :style="{
    'fontFamily': `'${css.family}'`,
  }">
    <div>
      <a href="https://vitejs.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
    <HelloWorld  msg="Vite + Vue" />
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
